CREATE TABLE CUSTOMER (
    ID INT AUTO_INCREMENT,
    FIRST_NAME VARCHAR(255),
    MIDDLE_NAME VARCHAR(255),
    SURNAME VARCHAR(255),
    INITIALS VARCHAR(255),
    TITLE VARCHAR(255),
    STREET_LINE1 VARCHAR(255),
    STREET_NAME VARCHAR(255),
    SUBURB VARCHAR(255),
    CITY VARCHAR(255),
    STATE VARCHAR(255),
    COUNTRY VARCHAR(255),
    PINCODE VARCHAR(255),
    SEX VARCHAR(255),
    MARITAL_STATUS VARCHAR(255),
    CREDIT_RATING INT,
    IS_NAB_CUSTOMER BOOLEAN
)